Initial Contribution
eclipse-esmf/esmf-aspect-model-editor-backend pull request #2
Opened 2022-07-06 15:00 UTC by michelu89

2022-07-11 14:15 UTC, atextor requested changes

2022-07-11 14:23 UTC, michelu89 commented on src/main/java/io/openmanufacturing/ame/repository/strategy/LocalFolderResolverStrategy.java
> +    * ex: io\openmanufacturing\1.0.0\AspectDefault.ttl -F io.openmanufacturing:1.0.0:AspectDefault.ttl
Comment will be adjusted because of typo.

2022-07-11 16:18 UTC, michelu89 commented on src/main/java/io/openmanufacturing/ame/services/utils/ModelUtils.java
> +         "^urn:[a-z0-9][a-z0-9-]{0,31}:([a-z0-9()+,\\-.:=@;$_!*#']|%[0-9a-f]{2})+$",
Unfortunately, the namespace pattern does not work.

2022-07-12 06:01 UTC, atextor approved these changes

2022-07-12 07:00 UTC, merged